apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probes
  name: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - image: nginx
        name: nginx 
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 9090
 